name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: i18n consistency check
        run: node scripts/check-i18n.js

      - name: Run unit tests (Vitest)
        run: npx vitest run --reporter=default

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npx vite build

      - name: Start preview server
        run: npx vite preview --port 8080 &

      - name: Wait for server
        run: npx --yes wait-on http://localhost:8080

      - name: Run E2E tests (Playwright)
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:8080
        run: npx playwright test
